### ISSUE TITLE
[bug]: Lnbits web interface fails to launch

### ISSUE THREAD

**Issue by mikeyb233** [Start9Labs/lnbits-startos#26]
### Prerequisites

- [X] I have searched for existing issues that already report this problem.

### Device

Laptop/Desktop

### Device OS

Linux

### Device OS Version

Start9 0.3.4~4

### Browser

Brave

### Browser Version

1.59.124

### Current Behavior

In Lnbits version 0.11.1 the web interface fails to load and the health check never completes. I see the logs that it's looking for an /mnt/lnd/admin.macaroon and says there is no file or directory. I currently use Core lightning as my lightning node.

### Expected Behavior

Lnbits health check completes and web interface launches when using a core lightning node

### Steps to Reproduce

Run core lightning
Run latest version of lnbits

**Comment by Dominion5254** [comment]
Is this behavior and error reproducible across restarts?

Can you share the exact error you are seeing in the logs? Additional logs to provide context for the error would be helpful as well, but be sure to remove sensitive data such as your onion url and your pubkey before sharing.

**Comment by mikeyb233** [comment]
Yes I have restarted Lnbits several times and restarted the machine but
still producing the same error.

What other logs would you like?

This is exact error from the Lnbits log (attached):

2023-11-02T21:49:02-04:00  xxd: /mnt/lnd/admin.macaroon: No such file or directory
2023-11-02T21:49:18-04:00  xxd: /mnt/lnd/admin.macaroon: No such file or directory
2023-11-02T21:49:34-04:00  xxd: /mnt/lnd/admin.macaroon: No such file or directory
2023-11-02T21:49:49-04:00  xxd: /mnt/lnd/admin.macaroon: No such file or directory
2023-11-02T21:50:05-04:00  xxd: /mnt/lnd/admin.macaroon: No such file or directory

**Comment by Dominion5254** [comment]
I found the cause and have a patch being tested. In the interim, just installing LND (while keeping CLN as the LNbits LN implementation) will allow you to use LNbits with CLN.

**Comment by mikeyb233** [comment]
Awesome. Thanks for your help!
