### ISSUE TITLE
[feat] Better Handling of Accounts

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/lnbits-startos#6]
Currently, "Launch UI" will lead the user to create a new wallet.  Realistically, the superuser account should probably be launched and will be sufficient on its own for most use cases.  There may be other considerations and trade-offs.

**Comment by islandbitcoin** [comment]
do we have the ability to customize the `LAUNCH UI` URL? 
I remember hearing it would be in an upcoming OS release

**Comment by kn0wmad** [comment]
This might be an 040 feature.  Another (much simpler) idea would be to add launch icons to the URLs in Properties

**Comment by Dominion5254** [comment]
This is actually solved by 0.12.1.

As of 0.12.1, Launch UI will only lead to the creation of a new user/wallet *if* there is not already a user logged in. If there is a user logged in, that account will be opened by Launch UI.
